# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_load_into_orthanc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load_into_orthanc.setGeometry(QtCore.QRect(230, 250, 231, 23))
        self.pushButton_load_into_orthanc.setObjectName("pushButton_load_into_orthanc")
        self.pushButton_download_from_orthanc_to_drive = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_download_from_orthanc_to_drive.setGeometry(QtCore.QRect(230, 510, 231, 23))
        self.pushButton_download_from_orthanc_to_drive.setObjectName("pushButton_download_from_orthanc_to_drive")
        self.lineEdit_excel_absolute_file_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_excel_absolute_file_path.setGeometry(QtCore.QRect(40, 120, 741, 20))
        self.lineEdit_excel_absolute_file_path.setObjectName("lineEdit_excel_absolute_file_path")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 501, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 241, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 541, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_select_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_file.setGeometry(QtCore.QRect(180, 90, 75, 23))
        self.pushButton_select_file.setObjectName("pushButton_select_file")
        self.lineEdit_excel_absolute_download_dir_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_excel_absolute_download_dir_path.setGeometry(QtCore.QRect(30, 450, 741, 20))
        self.lineEdit_excel_absolute_download_dir_path.setObjectName("lineEdit_excel_absolute_download_dir_path")
        self.pushButton_select_download_dir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_download_dir.setGeometry(QtCore.QRect(30, 420, 151, 23))
        self.pushButton_select_download_dir.setObjectName("pushButton_select_download_dir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_load_into_orthanc.setText(_translate("MainWindow", "load into orthanc"))
        self.pushButton_download_from_orthanc_to_drive.setText(_translate("MainWindow", "download from orthanc to Drive"))
        self.label.setText(_translate("MainWindow", "Download data from Pacs system into a local orthanc database"))
        self.label_2.setText(_translate("MainWindow", "select Data by Exel file"))
        self.label_3.setText(_translate("MainWindow", "Columnnames must be: PatientID, FamilyName, GivenName, BirthDate, StudyDate"))
        self.pushButton_select_file.setText(_translate("MainWindow", "select File"))
        self.pushButton_select_download_dir.setText(_translate("MainWindow", "select download Dir"))
